import { Roboto } from "next/font/google"
import "./globals.css"
import { StepsProvider } from "@/contexts/TaskStepContext"


const roboto = Roboto({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StepsProvider>{children}</StepsProvider>
      </body>
    </html>
  )
}
